name: Run lint

on:
  pull_request:

jobs:

  rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Ruby
        uses: ruby/setup-ruby@v4
        with:
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop